# Generated by Django 4.0.6 on 2023-03-05 13:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=50, verbose_name='Brand')),
                ('Foto', models.FileField(upload_to='images/')),
                ('Tarix', models.DateField(auto_now=True)),
                ('user_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ad', models.CharField(max_length=50, verbose_name='Ad')),
                ('Soyad', models.CharField(max_length=50)),
                ('Tel', models.CharField(max_length=50)),
                ('Foto', models.FileField(upload_to='images/')),
                ('Email', models.EmailField(max_length=50)),
                ('Sirket', models.CharField(max_length=50)),
                ('Tarix', models.DateField(auto_now=True)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ishciler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50)),
                ('soyad', models.CharField(max_length=50)),
                ('telefon', models.CharField(max_length=50)),
                ('ev_tel', models.CharField(max_length=50)),
                ('unvan', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mehsul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ad', models.CharField(max_length=50)),
                ('Foto', models.FileField(upload_to='images/')),
                ('Alish', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(1000), django.core.validators.MinLengthValidator(0)])),
                ('Satish', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(1000), django.core.validators.MinLengthValidator(0)])),
                ('Miqdar', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(1000), django.core.validators.MinLengthValidator(0)])),
                ('user_id', models.CharField(max_length=50)),
                ('Brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brands')),
            ],
        ),
        migrations.CreateModel(
            name='Shobe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(blank=True, max_length=50)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Xercler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teyinat', models.CharField(max_length=50)),
                ('Mebleg', models.CharField(max_length=50)),
                ('Tarix', models.DateField(auto_now=True)),
                ('user_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vezife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('ad', models.CharField(max_length=50)),
                ('shobe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shobe')),
            ],
        ),
        migrations.CreateModel(
            name='Sifaris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Miqdar', models.CharField(max_length=50)),
                ('Tesdiq', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(1000), django.core.validators.MinLengthValidator(0)])),
                ('Tarix', models.DateField(auto_now=True)),
                ('user_id', models.CharField(max_length=50)),
                ('Client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clients')),
                ('Mehsul_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mehsul')),
            ],
        ),
        migrations.CreateModel(
            name='Senedler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basliq', models.CharField(max_length=50)),
                ('skan', models.FileField(upload_to='images/')),
                ('qeyd', models.CharField(max_length=50)),
                ('user_id', models.IntegerField()),
                ('ishci_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ishciler')),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(upload_to='images/')),
                ('us', models.CharField(max_length=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ishciler',
            name='vezife_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vezife'),
        ),
    ]
